### ISSUE TITLE
Turn on Discussion section on the project for discussions

### ISSUE THREAD

**Issue by Makuna** [cpldcpu/Gen2-Addressable-RGB#1]
Or do you want us to use Issues for discussions?

My first question is about the Y branching.  If you capture the normal color data output for a config that has a branch, is the output still the same as WS2812?   
The key thing I am trying to get an answer for is...
 ... does the "string" address represent the order of the color data, such that address 0x01 "pixels" are all sent followed by address 0x02 "pixels" such that normal WS12812 is used for all color data output?

**Comment by cpldcpu** [comment]
Excellent idea, discussions are enabled now!

https://github.com/cpldcpu/Gen2-Addressable-RGB/discussions

> My first question is about the Y branching. If you capture the normal color data output for a config that has a branch, is the output still the same as WS2812?
> The key thing I am trying to get an answer for is...
> ... does the "string" address represent the order of the color data, such that address 0x01 "pixels" are all sent followed by address 0x02 "pixels" such that normal WS12812 is used for all color data output?

Exactly. Once a substring is activated, the system will basically behave as if the other strings don't exist and the activated string behaves like a normal WS2812 string (+some extensions).

**Comment by Makuna** [comment]
I see you ran into the problem of when do you close an issue.  Github doesn't have the RESOLVE state, not the same as closed/completed.  Project managers resolve, user is given the chance to close as a means to agree, managers will close if the user doesn't close in a reasonable time (month?)

I handle this by using the "labels" to have one label for "resolved"

**Comment by cpldcpu** [comment]
I thought to keep it open so people are reminded to check out discussion before opening an issue. But its also fine to close.
